service: thumbnail-generator

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  profile: serverless-admin
  region: eu-west-1
  stage: dev
  timeout: 10
  memorySize: 128
  environment:
    THUMBNAIL_SIZE: 128
    REGION_NAME: ${self:provider.region}
    DYNAMODB_TABLE: ${self:custom.dynamoTable}

  # Setup IAM Roles
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 'S3:*'
        - Effect: 'Allow'
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

custom:
  bucket: my-thumbnails-rob
  dynamoTable: image-url-table
  pythonRequirements:
  # Prepare the dependencies using a Linux environment 
    dockerizePip: true

functions:
  thumbnail_generator:
    handler: handler.thumbnail_generator
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png

  list:
    handler: handler.list_thumbnail_urls
    events:
      - http:
          path: images/all
          method: get 
          # Cross Origin Resource Sharing
          cors: true
  get:
    handler: handler.get_item
    events:
      - http:
          # id comes from attribute name
          path: images/get/{id}
          method: get 
          cors: true

resources:
  Resources:
    ImagesDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
          # String
            AttributeType: S
        KeySchema:
          - AttributeName: id
            # Every row has a unique primary key in the DB
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}

plugins:
  # automatically bundle dependencies from requirements.txt and make them
  # available in PYTHONPATH
  - serverless-python-requirements